pipeline {
    agent any

    environment {
        // Optional: virtual environment or test DB vars can go here
        APP_DIR = 'messaging_app'
    }

    stages {
        stage('Checkout Code') {
            steps {
                git branch: 'main',
                    credentialsId: 'github-credentials',
                    url: 'https://github.com/Kiproy04/alx-backend-python.git'
            }
        }

        stage('Install Dependencies') {
            steps {
                sh '''
                    echo "Installing dependencies..."
                    pip3 install --upgrade pip
                    pip3 install -r ${APP_DIR}/requirements.txt
                '''
            }
        }

        stage('Run Tests') {
            steps {
                sh '''
                    echo "Running pytest..."
                    pytest --maxfail=1 --disable-warnings -q --junitxml=report.xml
                '''
            }
        }

        stage('Archive Test Report') {
            steps {
                junit 'report.xml'
            }
        }
    }

    post {
        always {
            echo 'Pipeline finished — cleaning up workspace.'
            cleanWs()
        }
    }
}

